language: python

sudo: false

env:
    - TARGET=unit

python:
    - "2.7"

services:
    - mongodb
    - redis-server

cache:
  directories:
    - $HOME/.cache/pip

install:
    - if [ "${TARGET}" = "unit" ] ; then
        pip install -r dev-requirements.txt && pip install coveralls==1.0a2;
      fi

script:
    - if [ "${TARGET}" = "unit" ]; then
        flake8;
        nosetests --with-coverage;
      fi

after_script:
    - killall -9 python
